server:
  port: 8080

swagger:
  gateway: ${GATEWAY:https://localhost:9000/user-service/}

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

access:
  time: ${ACCESS_TIME:3600000}
  key: ${ACCESS_KEY:FMXhpZGDSOioookMXXbaYeWvONaoydra}

clients:
  mail-service: ${MAIL_SERVICE_URI:http://mail-service}